steps:
  # Step 1: Install Terraform
  - name: 'hashicorp/terraform:1.7.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform init
        terraform plan -out=tfplan
        terraform apply -auto-approve tfplan

# Use the service account created above
serviceAccount: terraform-builder@chatverse-475212.iam.gserviceaccount.com

# Optional: set a bucket for state (recommended)
options:
  logging: CLOUD_LOGGING_ONLY
